Compliance features
kilnfi/staking-contracts pull request #101
Opened 2024-11-09 04:20 UTC by 0xvv

2024-12-03 10:46 UTC, loicttn requested changes

2024-12-03 10:46 UTC, loicttn commented on README.md
> +Admin can also block an address by calling `ban(address, bytes)` on the contract. This will prevent the address from depositing, exiting or withdrawing. And force the exit of the validators provided
> And force the exit of the validators provided if provided and the user is not sanctioned.

to rephrase

2024-12-03 10:46 UTC, loicttn commented on README.md
> +Admin can also block an address by calling `ban(address, bytes)` on the contract. This will prevent the address from depositing, exiting or withdrawing. And force the exit of the validators provided
so it force exit but does not allow to withdraw what was force exit?

2024-12-03 10:46 UTC, loicttn commented on src/contracts/StakingContract.sol
> +                revert Unauthorized();
maybe a more specific error?

2024-12-03 10:46 UTC, loicttn commented on src/contracts/StakingContract.sol
> +            emit ExitRequest(withdrawer, publicKey);
TBD by eng team: do we need to also add an extra ForceExit event for indexing?

2024-12-03 10:46 UTC, loicttn commented on src/contracts/StakingContract.sol
> +    function isBlocked(address _account) public view returns (bool) {
maybe makes more sense to return [sanctioned, blocked] wdyt?

2024-12-03 10:46 UTC, loicttn commented on src/test/StakingContract.t.sol
> +        stakingContract.deposit{value: 32 ether}();
shouldn't we check there is a deposit event emitted here?

2024-12-03 10:46 UTC, loicttn commented on src/contracts/StakingContract.sol
> +        _revertIfSanctionedOrBlocked(withdrawer);
so if you are blocked, not even the admin can force-withdraw you?

2024-12-03 10:48 UTC, loicttn commented on src/contracts/StakingContract.sol
> +        _revertIfSanctionedOrBlocked(withdrawer);
maybe this should be msg.sender, lm double check the requirements

2024-12-03 10:49 UTC, 0xvv commented on README.md
> +Admin can also block an address by calling `ban(address, bytes)` on the contract. This will prevent the address from depositing, exiting or withdrawing. And force the exit of the validators provided
After the stakes are exited and skimmed the admin can push them to the users by calling the recipients directly

2024-12-03 10:52 UTC, 0xvv commented on src/contracts/StakingContract.sol
> +    function isBlocked(address _account) public view returns (bool) {
why not

2024-12-03 10:54 UTC, 0xvv commented on src/test/StakingContract.t.sol
> +        stakingContract.deposit{value: 32 ether}();
Yep, I left out the changes to the test files to push the code to review asap many cases are not covered by what is currently pushed

2024-12-03 12:26 UTC, 0xvv commented on src/contracts/StakingContract.sol
> +                revert Unauthorized();
Actually refactored to use a shared internal function with the usual exit flow so it'll be the same error, this is an admin function so it's ok imo

2024-12-03 12:26 UTC, 0xvv commented on src/contracts/StakingContract.sol
> +    function isBlocked(address _account) public view returns (bool) {
done

2024-12-03 12:26 UTC, 0xvv commented on README.md
> +Admin can also block an address by calling `ban(address, bytes)` on the contract. This will prevent the address from depositing, exiting or withdrawing. And force the exit of the validators provided
rephrased

2024-12-03 12:30 UTC, 0xvv commented on src/contracts/StakingContract.sol
> +        _revertIfSanctionedOrBlocked(withdrawer);
here `msg.sender` is either the withdrawer or the admin

2025-02-04 15:21 UTC, loicttn approved these changes

2025-02-04 15:21 UTC, merged